import type { Metadata } from "next";

import { Inter } from "next/font/google";

import { LayoutProvider } from "@/contextStore/layout-context";

import Menu from "./components/menu";

import "./globals.css";
import About from "./components/about";
import Copyright from "./components/copyright";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  // pathname: string;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProvider>
          <div className="overflow-y-hidden overflow-x-scroll w-screen h-screen flex p-0 items-center">
            <Menu />
            {children}
            <About />
            <Copyright />
          </div>
        </LayoutProvider>
        </body>
    </html>
  );
}
